name: zzztest5

on:
  workflow_dispatch:
    inputs:
      aaa:
        description: 'aaaです'
        required: true
        default: 'V6'
      bbb:
        description: 'bbbです'
        required: true
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - 
        run: |
          echo "sanuki111!!!!"
          echo "${{ github.event.inputs.aaa }}"
          echo "${{ github.event.inputs.bbb }}"


