name: zzztest3


on:
  workflow_dispatch:
  
  push:
    tags:
      - 'v[0-9]+'
      
permissions:
  contents: write
  
jobs:
  ttjob1:
    runs-on: ubuntu-latest
    steps:
      - 
        run: |
          echo "タグが追加されたよ!!"
          echo "${{github.ref}}"
          echo "${{github.ref_name}}"

      #- 
      #  uses: actions/checkout@v3

      #- 
      #  run: git tag -d ${{github.ref_name}}

      - name:
        run: git push --delete origin ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
          
