name: zzztest4

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    
      -
        run: |
          echo "sha=${{ github.sha }}"
          echo "sha=${{ github.ref_name }}"
    
      - 
        uses: actions/checkout@v3

      - 
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: user/myimage
          tags: |
            type=ref,event=branch
            type=sha
            type=sha, format=long
            #type=ref,event=branch
            #type=ref,event=tag
            #type=ref,event=pr
            #type=sha
            #type=edge
            #type=raw,value=latest

      - name: Print metadata
        run: |
          echo "------------------------------------------"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "------------------------------------------"
          echo "Labels: ${{ steps.meta.outputs.labels }}"
          echo "------------------------------------------"
