name: zzztest7

on:
  workflow_dispatch:
    inputs:
      tag_name1:
        description: 'tag name1です'
        required: true
      tag_name2:
        description: 'tag name2です'
        required: true
      tag_name3:
        description: 'tag name3です(削除)'
        required: true

jobs:

  job0:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      #-------------------------------------------------------
      #タグ削除(使わない場合はコメントアウト)
      - 
        run: |
          git tag -d ${{ github.event.inputs.tag_name3 }}

      - 
        run: |
          git push origin --delete ${{ github.event.inputs.tag_name3 }}

      #-------------------------------------------------------
      #タグ追加
      - 
        run: |
          git tag ${{ github.event.inputs.tag_name1 }}

      - 
        run: |
          git push origin ${{ github.event.inputs.tag_name1 }}

      #-------------------------------------------------------

  job1:
    runs-on: ubuntu-latest
      
    steps:

      - run: |
          echo "sleep開始"
          #sleep 60
          echo "sleep終了"

  job2:
    needs: job1
    uses: ./.github/workflows/zzztest7_sub.yml
    permissions:
      contents: write

