name: zzztest6

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag nameです'
        required: true
      commit_hash:
        description: 'commit hashです'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:

      - run: |
          echo "sleep開始"
          sleep 180
          echo "sleep終了"

      - 
        uses: actions/checkout@v3
        #with:
          #fetch-depth: 0
          #ref:  ${{ github.event.inputs.commit_hash }}
      
      
      - 
        run: |
          git tag ${{ github.event.inputs.tag_name }}

      - 
        run: |
          git push --tags

