name: zzztest8

on:
  push:
    tags:
      - 'a*'

jobs:
  generate-metadata:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - 
        run: |
          cat test.txt
      
      - 
        run: |
          echo "hash=${{ github.sha }}"
          echo "hash=$(echo ${{ github.sha }} | cut -c1-7)"

      - 
        run: |
          echo "タグ=${{ github.ref }}"
          echo "タグ=${{ github.ref_name }}"
          git tag --contains ${{ github.sha }}
      