name: zzztest7_sub

on:
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - 
        uses: actions/checkout@v3
      
      - 
        run: |
          git tag ${{ github.event.inputs.tag_name }}

      - 
        run: |
          git push --tags
