name: zzztest7

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag nameです'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
      
    steps:

      - run: |
          echo "sleep開始"
          sleep 10
          echo "10"
          sleep 10
          echo "20"
          sleep 10
          echo "30"
          sleep 10
          echo "40"
          sleep 10
          echo "50"
          sleep 10
          echo "60"
          sleep 10
          echo "70"
          sleep 10
          echo "80"
          sleep 10
          echo "90"
          echo "sleep終了"

  job2:
    needs: job1
    uses: ./.github/workflows/zzztest7_sub.yml

