name: zzztest6

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag nameです'
        required: true
      commit_hash:
        description: 'commit hashです'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - 
        run: |
          git tag ${{ github.event.inputs.tag_name }} ${{ github.event.inputs.commit_hash }}

      - 
        run: |
          git push origin ${{ github.event.inputs.tag_name }} 
