name: zzztest7

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag nameです'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
      
    steps:

      - run: |
          echo "sleep開始"
          sleep 120
          echo "sleep終了"

  job2:
    needs: job1
    uses: ./.github/workflows/zzztest7_sub.yml

